import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import PageWrapper from "@/components/PageWrapper";
import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Preload fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          rel="preload"
          href="https://fonts.googleapis.com/css2?family=Roboto+Serif:wght@100..900&family=Roboto:wght@100..900&display=swap"
          as="style"
          onLoad="this.onload=null;this.rel='stylesheet'"
        />
        <noscript>
          <link
            href="https://fonts.googleapis.com/css2?family=Roboto+Serif:wght@100..900&family=Roboto:wght@100..900&display=swap"
            rel="stylesheet"
          />
        </noscript>

        {/* Preload global styles */}
        <link rel="preload" href="/globals.css" as="style" onLoad="this.onload=null;this.rel='stylesheet'" />
        <noscript><link rel="stylesheet" href="/globals.css" /></noscript>

        {/* Inline critical CSS */}
        <style>
          {`
            body { font-family: 'Roboto', sans-serif; }
          `}
        </style>
      </head>
      <body>
        <Navbar />
        <PageWrapper>{children}</PageWrapper>
        <Footer />
      </body>
    </html>
  );
}
