import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import PageWrapper from "@/components/PageWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <PageWrapper> {/* Wrap children inside PageWrapper */}
          {children}
        </PageWrapper>
        <Footer />
      </body>
    </html>
  );
}